### PR TITLE
Add Docker Support

### PR DESCRIPTION
**Pull request by krubenok**
# Description

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by srandall97** [comment]
Are you working on this still?

**Comment by krubenok** [comment]
Nope!

**Pull request merged**
